; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:d1_wroom_02]
platform = espressif8266
board = d1_wroom_02
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200

lib_deps =
    pu2clr/PU2CLR RDA5807@^1.1.9
    bblanchon/ArduinoJson@^7.2.2
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
